channels:
- conda-forge
dependencies:
- python=3.10.14
- pip<=24.0
- pip:
  - mlflow==2.13.0
  - cloudpickle==3.0.0
  - packaging==24.0
  - psutil==5.9.8
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - typing-extensions==4.10.0
name: mlflow-env
